# Generated by Django 4.2.1 on 2023-07-02 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
