# Generated by Django 4.2.1 on 2023-07-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_relationship'),
        ('blog', '0002_alter_post_options_post_created_post_liked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='likes', to='users.profile'),
        ),
    ]
